title: Node.js Tutorial for Noobs
description: This is a Nodejs Tutorial for Absolute Beginers in Programming
theme: jekyll-theme-cayman
# remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
plugins:
  - jemoji 
  # - jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"